name: iLand
main: davidglitch04\iLand\iLand
api: 4.0.0
version: 1.0.1
author: DavidGlitch04
website: https://github.com/DavidGlitch04
description: "Powerful land plugin, based on PMMP."
extensions:
  core: ">=8.0"

permissions:
  iland.allow.command:
    description: "Allow player to use iLand"
    default: op